### PR TITLE
Fix cropped footer

### PR DESCRIPTION
**Pull request by ghost**
A PR that fixes the cropped footer problem for all themes. The footer is now in a fixed position, tied to the bottom of the view, as it should be.

### CODE REVIEW

**Comment by exstral** [comment]
Thanks for the pull request, screenshots and all, very nice!

But I'm thinking, if the issue affects all themes, we should probably try to fix it in the core mastodon css instead of only in this one theme.

Do you think this is an issue introduced by hometown or us? I can check tomorrow if it exists already in the base `hometown-dev` branch.

**Comment by ghost** [comment]
> Thanks for the pull request, screenshots and all, very nice!
> 
> But I'm thinking, if the issue affects all themes, we should probably try to fix it in the core mastodon css instead of only in this one theme.
> 
> Do you think this is an issue introduced by hometown or us? I can check tomorrow if it exists already in the base `hometown-dev` branch.

Yup I think it's a problem introduced in mastodon, but it's worth looking into the hometown branch as well. I tried modifying this for our theme only to see what you all think, but I'll look into how to fix it for all themes. I guess mastodon peeps didn't think that the footers would get too big.

**Comment by exstral** [comment]
Oh right, this is because we have such a big footer. Still I think we should fix it in the mastodon base css then, and not only in our theme. Because our users also use different themes. Can you change this pull request to change it there instead? :)

**Comment by ghost** [comment]
> Oh right, this is because we have such a big footer. Still I think we should fix it in the mastodon base css then, and not only in our theme. Because our users also use different themes. Can you change this pull request to change it there instead? :)

Yup. I completely agree, was gonna push my edits to that today. I need to find the best place to place the edit first :)

**Pull request closed without merging**
